services:
  app1:
    build:
      context: ./app1
    ports:
      - 3000:3000
    command: node server.js
  app2:
    build:
      context: ./app2
    ports:
      - 4000:4000
    command: node server.js
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - app1
      - app2