services:
  lb:
    build: 
      context: lb
      dockerfile: Dockerfile
    command: node lb.js
    ports:
      - 8000:8000
    networks:
      - my_network
    depends_on:
      - app1
      - app2
  app1:
    build: 
      context: app1
      dockerfile: Dockerfile
    command: node server.js    
    networks:
      - my_network
  app2:
    build: 
      context: app2
      dockerfile: Dockerfile
    command: node server.js    
    networks:
      - my_network
networks:
  my_network: